name: Create Project Secrets
on:
  workflow_dispatch:

jobs:
  createVariables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:
      env:
        GITHUB_TOKEN: ${{ secrets.GON_GITHUB_TOKEN }}
      run: |
        gh secret set --env Development -f dev_secrets.txt
        gh secret set --env Production -f prod_secrets.txt
        gh secret set -f repo_secrets.txt
        
