name: Create Project Secrets
on:
  workflow_dispatch:

jobs:
  createVariables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:
      env:
        GITHUB_TOKEN: ${{ secrets.GON_GITHUB_TOKEN }}
      run: |
        gh secret set MULE_ORG_ID -b "fc9e3283-a489-4e88-99aa-cceea4aa5ea1" --repos example-github-1
