name: Create Project variables
on:
  workflow_dispatch:

jobs:
  createVariables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:
      env:
        GITHUB_TOKEN: ${{ secrets.GON_GITHUB_TOKEN }}
      run: |
      # gh auth status
        gh variable set -f project_variables.txt

      # gh variable set API_LAYER --body "System"
      #  gh variable set CORES --body "0.1"
      #  gh variable set REPLICAS --body "1"
      #  gh variable set ASSET_ID --body "slack-system-api"
      #  gh variable set ASSET_VERSION --body "1.0.1"
