name: Deploy to Prod

# Controls when the workflow will run
on:
 # pull_request:
 #   branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  deploy_to_Prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Cloudhub PROD
      env:
        MULE_CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }}
        MULE_CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }}
        MULE_ORG_ID: ${{ secrets.MULE_ORG_ID }}
        SECURE_KEY: ${{ secrets.SECURE_KEY }}
        client_id: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}
        client_secret: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
        environment: ${{ vars.ENVIRONMENT }}
        target: ${{ vars.TARGET }}
        api_id: ${{ vars.API_ID }}
        replicas: ${{ vars.REPLICAS }}
        cores: ${{ vars.CORES }}
        api_layer: ${{ vars.API_LAYER }}
        app_env: ${{ vars.APP_ENV }}
      run: |
        mvn clean -B deploy -DmuleDeploy -s .maven/settings.xml
  testAPI:
    needs: deploy_to_Prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install Node on the runner
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    # Install Newman
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    # Run tests
    - name: Run tests
      run: |
        newman run postman/testing/prod/app-prod-testing-collection.json -e postman/testing/prod/app-prod-testing-environment.json   
