name: Test conditional
on:
  workflow_dispatch:

jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
    - name: Echo cero
      if: ${{ vars.API_ID != 0000 }}
      run: echo Es cero
    - name: Echo uno
      if: ${{ vars.API_ID == 0000 }}
      run: Echo cero
    
